

CREATE TABLE [dbo].[Telefonos](
	[IdTelefono] [UNIQUEIDENTIFIER] NOT NULL,
	[Nombre] [VARCHAR](50) NOT NULL,
	[Direccion] [VARCHAR](150) NOT NULL,
	[Telefono] [VARCHAR](20) NOT NULL,
	[Nota] [VARCHAR](150) NULL,
	[FechaCreacion] [DATETIME] NOT NULL,
 CONSTRAINT [PK_Telefonos] PRIMARY KEY CLUSTERED 
(
	[IdTelefono] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


